#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst

import glob
import os
import sys
from setuptools import setup, find_packages, Command
import subprocess

# Get some values from the setup.cfg
from configparser import ConfigParser

conf = ConfigParser()
conf.read(['setup.cfg'])
metadata = dict(conf.items('metadata'))

PACKAGENAME = metadata['package_name']
DESCRIPTION = metadata['description']
AUTHOR = metadata['author']
AUTHOR_EMAIL = metadata['author_email']
LICENSE = metadata['license']
URL = metadata['url']

with open('LONG_DESCRIPTION.rst') as f:
    LONG_DESCRIPTION = f.read()

# VERSION should be PEP440 compatible (http://www.python.org/dev/peps/pep-0440)
VERSION = metadata.get('version')

# Indicates if this version is a release version
RELEASE = 'dev' not in VERSION

if not RELEASE:
    try:
        import re
        git_description = subprocess.check_output(['git', 'describe', '--tags']).decode('utf-8').strip()
        tags = subprocess.check_output(['git', 'tag']).decode('utf-8').strip().split('\n')
        for tag in tags:
            git_description = git_description.replace(tag, '')
        git_description = re.sub('^v', '', git_description)
        git_description = re.sub('-([0-9]+)-', '.dev\\1+', git_description)
        git_description = re.sub('-g([0-9a-zA-Z]+)', '+\\1', git_description)
        VERSION += git_description
    except (subprocess.CalledProcessError, OSError):
        pass

# Custom commands to provide helpful messages to users
class TestCommand(Command):
    description = "Run tests using pytest"
    user_options = []
    
    def initialize_options(self):
        pass
    
    def finalize_options(self):
        pass
    
    def run(self):
        print("""
Note: running tests is no longer done using 'python setup.py test', but
instead you will need to run the following command:

    tox -e test

If you don't already have tox installed, you can install it with:

    pip install tox

For more information, see https://docs.astropy.org
""")
        sys.exit(1)

class BuildDocsCommand(Command):
    description = "Build the documentation"
    user_options = []
    
    def initialize_options(self):
        pass
    
    def finalize_options(self):
        pass
    
    def run(self):
        print("""
Note: building the documentation is no longer done using 'python setup.py build_docs',
but instead you will need to run the following command:

    tox -e build_docs

If you don't already have tox installed, you can install it with:

    pip install tox

For more information, see https://docs.astropy.org
""")
        sys.exit(1)

# Define custom commands
cmdclassd = {
    'test': TestCommand,
    'build_docs': BuildDocsCommand,
}

# Treat everything in scripts except README* as a script to be installed
scripts = [fname for fname in glob.glob(os.path.join('scripts', '*'))
           if not os.path.basename(fname).startswith('README')]

# Define entry points for command-line scripts
entry_points = {'console_scripts': []}

if conf.has_section('entry_points'):
    entry_point_list = conf.items('entry_points')
    for entry_point in entry_point_list:
        entry_points['console_scripts'].append('{0} = {1}'.format(
            entry_point[0], entry_point[1]))

# Get package data
package_data = {}
package_data[PACKAGENAME] = ['data/*']

# Include all .c files, recursively, including those generated by
# Cython, since we can not do this in MANIFEST.in with a "dynamic"
# directory name.
c_files = []
for root, dirs, files in os.walk(PACKAGENAME):
    for filename in files:
        if filename.endswith('.c'):
            c_files.append(
                os.path.join(
                    os.path.relpath(root, PACKAGENAME), filename))
if c_files:
    package_data[PACKAGENAME].extend(c_files)

install_requires = [
    'numpy>=1.11',
    'astropy>=1.3',
    'astropy-healpix',
    'scikit-image',
    'Pillow',
]

extras_require = dict(
    recommended=[
        'matplotlib>=2.0',
        'reproject>=0.3.1',
        'tqdm',
        'aiohttp',
    ],
    develop=[
        'matplotlib>=2.0',
        'reproject>=0.3.1',
        'pytest>=3.0',
        'mypy>=0.501',
        'tqdm',
        'aiohttp',
    ],
)

classifiers = [
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: Implementation :: CPython',
    'Topic :: Scientific/Engineering :: Astronomy',
    'Development Status :: 3 - Alpha',
]

setup(
    name=PACKAGENAME,
    version=VERSION,
    description=DESCRIPTION,
    scripts=scripts,
    install_requires=install_requires,
    extras_require=extras_require,
    author=AUTHOR,
    author_email=AUTHOR_EMAIL,
    license=LICENSE,
    url=URL,
    long_description=LONG_DESCRIPTION,
    classifiers=classifiers,
    packages=find_packages(),
    package_data=package_data,
    zip_safe=False,
    use_2to3=False,
    entry_points=entry_points,
    cmdclass=cmdclassd,
)
